### ISSUE TITLE
get_lessons fetches lessons in wrong order, sometimes skips lessons altogether, or fetches one lesson multiple times

### ISSUE THREAD

**Issue by XgamiX** [kapi2289/vulcan-api#131]
example:
08:50-09:35 Bezpieczeństwo i higiena pracy
09:50-10:35 Systemy operacyjne
10:40-11:25 Język polski
11:30-12:15 Język angielski
12:30-13:15 Zajęcia z wychowawcą
14:10-14:55 Język niemiecki
15:00-15:45 Język niemiecki
08:00-08:45 Systemy operacyjne
11:30-12:15 Język angielski
13:20-14:05 Język niemiecki

**Comment by kuba2k2** [comment]
You didn't add your code that generated this list. I don't think that lessons are returned in any particular order anyway.

**Comment by XgamiX** [comment]
Thank you for the advice.
