### ISSUE TITLE
cannot import name 'Vulcan' from 'vulcan'

### ISSUE THREAD

**Issue by bartekpacia** [kapi2289/vulcan-api#20]
Hej, poległem szybko, bo już na importowaniu tego pakietu.

```python
import json
import requests
from vulcan import Vulcan

print("here")
```

Logi:
```
Traceback (most recent call last):
  File "vulcan.py", line 3, in <module>
    from vulcan import Vulcan
  File "/Users/bartekpacia/dev/python/vulcan/vulcan.py", line 3, in <module>
    from vulcan import Vulcan
ImportError: cannot import name 'Vulcan' from 'vulcan'
```

Naprawdę nie wiem co robię źle, pakiet oczywiście zainstalowany przez PIPa. Moduł jest importoway, ale chyba po prostu nie umie znaleźć klasy `Vulcan`

pomocy

**Comment by kapi2289** [comment]
Sprawdź najpierw czy biblioteka się w ogóle zainstalowała używając po prostu `import vulcan`. Upewnij się też, czy zainstalowałeś bibliotekę na odpowiednią wersję pythona.

**Comment by bartekpacia** [comment]
Tak, biblioteka jest zainstalowana, samo `import vulcan` działa. Używam Pythona 3.7.4. Jakieś pomysły?

**Comment by kapi2289** [comment]
`vulcan.Vulcan` w takim razie działa? Spróbuj też sprawdzić wersję biblioteki przy użyciu `vulcan.__version__`

**Comment by kapi2289** [comment]
Zauważyłem też że pracujesz w pliku `vulcan.py`. Może Python importuje coś innego?

**Comment by bartekpacia** [comment]
Masz rację, po zmianie nazwy pliku na `app.py` biblioteka jest znajdywana poprawnie i wszystko działa.
Po drodze natknąłem się na problem z zapisaniem certyfikatu do pliku z użyciem kodu z dokumentacji. Ten poniżej dawał jakieś wyjątki (brak permisji)

```python
with open('cert.json') as f:
    f.write(json.dumps(certyfikat))
```

użyłem tego
```python
f =  open('cert.json', "w")
f.write(json.dumps(certyfikat))
f.close()
```

i wszystko śmiga

**Comment by kapi2289** [comment]
W pierwszym zapomniałeś dodać do funkcji `open` parametru `'w'`. Tak właściwie nie ty zapomniałeś, a ja napisałem źle w dokumentacji. Błąd już poprawiłem i powinno już być napisane poprawnie, pozdrawiam!
