### ISSUE TITLE
TypeError: Object of type Certificate is not JSON serializable

### ISSUE THREAD

**Issue by n3rsti** [kapi2289/vulcan-api#27]
When trying to register using this code:

```python
from vulcan import Vulcan
import json

certificate = Vulcan.register('token, 'symbol', 'pin')

with open('cert.json', 'w') as f: # You can use other filename
    json.dump(certificate, f)
```
i get this error:

(venv) n3rsti@n3rsti:~/repo/vulcan$ python3 register.py 
Registering...
Registered successfully!
Traceback (most recent call last):
  File "register.py", line 7, in <module>
    json.dump(certificate, f)
  File "/usr/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Certificate is not JSON serializable

**Comment by n3rsti** [comment]
Probably certification format has changed. It's object with pfx, key, key_formatted, base_url parameters

**Comment by HunterAzar** [comment]
Hi!!!!!

Try to get new certificate and transform to json
For example
`Certificate(pfx='LFKGJHDFG8DF9G8DFYU9H8BGUH98SFGU', key='GD88876SG8768H6FG98H6FGS', key_formatted='U4-U4-U4-U4-U4-U4-U4-U4', base_url='https://lekcjaplus.vulcan.net.pl/powiatpszczynski/')
`
Change to
`{
	"CertyfikatPfx": "'LFKGJHDFG8DF9G8DFYU9H8BGUH98SFGU",
	"CertyfikatKlucz": "GD88876SG8768H6FG98H6FGS",
	"CertyfikatKluczSformatowanyTekst": "U4-U4-U4-U4-U4-U4-U4-U4",
	"AdresBazowyRestApi": "https://lekcjaplus.vulcan.net.pl/powiatpszczynski/"
}
`
Where 
"CertyfikatPfx" == 'pfx'
"CertyfikatKlucz" == 'key'
"CertyfikatKluczSformatowanyTekst" == 'key_formatted'
"AdresBazowyRestApi" == 'base_url'

**Comment by HunterAzar** [comment]
If working close

**Comment by n3rsti** [comment]
@HunterAzar it's not in docs, but is there any parameter for fetching messages?

**Comment by HunterAzar** [comment]
I think there isn't any method for fetching messages

**Comment by kapi2289** [comment]
No, there isn't. If you want you can create PR and add it by yourself or I'll try to add this feature in future.

**Comment by HunterAzar** [comment]
Dobrze by było zrobic coś z tymi certyfikatami

**Comment by kapi2289** [comment]
My fault!
I've updated the documentation: https://github.com/kapi2289/vulcan-api/commit/9d68a15116a2aaca5888ae9a89e327744be41a2e#diff-528d58877abae2b411a047d62649a4b4
Now if you follow the documentation everything should be fine, sorry!

**Comment by HunterAzar** [comment]
Message support will be published tomorrow
