### ISSUE TITLE
Get all teachers

### ISSUE THREAD

**Issue by HunterAzar** [kapi2289/vulcan-api#29]
How can i get all teachers (name, id etc.)

**Comment by HunterAzar** [comment]
SOLVE: get_teachers() in _dictonaries.py

**Comment by kapi2289** [comment]
When I'll release `v1.1.0` you'll be able to fetch all teachers using
```python
client.dictionaries.teachers
```

**Comment by HunterAzar** [comment]
Ok
Thanks
