### ISSUE TITLE
Async branch

### ISSUE THREAD

**Issue by kpostekk** [kapi2289/vulcan-api#33]
I have created fork of this api and replaced `requests` library with `aiohttp` to increase performance and get away with [GIL related issues](https://bulldogjob.pl/articles/1081-gil-koniec-z-katarem-wez-asyncio).

Major changes:
 - Methods are now coroutines (requires an `await` keyword to run)
 - `Vulcan.__init__()` can't be a coroutine, so initialisation is done by coroutine `async Vulcan.create(certificate, logging_level=None)`

Could you create async branch?

Fork is [here](https://github.com/kpostekk/vulcan-api)
Real use examples are [here](https://gist.github.com/kpostekk/2d2f25516a5ba04899e9d7fa10748c04)

**Comment by kapi2289** [comment]
I've just created the `async` branch. You can now make a PR to it. Thanks for your contribution! 🎉
