### ISSUE TITLE
TypeError: ("'second_name' must be (<class 'str'>,) (got None that is a <class 'NoneType'>).")

### ISSUE THREAD

**Issue by Rei-666** [kapi2289/vulcan-api#50]
When I'm trying to initialize Vulcan object by `client = Vulcan(certificate)`, error is raised that "second_name" is None, which is true. When I add `student['Imie2'] = ""` in Student class in get method, everything works as expected.

      def get(cls, api):
          j = api.post(api.base_url + "UczenStart/ListaUczniow")
      
          for student in j.get("Data", []):
              student['Imie2'] = ""
              yield to_model(cls, cls.format_json(student))

**Comment by kapi2289** [comment]
Can you try seeing if #51 fixes your problem?
