### ISSUE TITLE
Is it possible to get attachments from homework?

### ISSUE THREAD

**Issue by Rei-666** [kapi2289/vulcan-api#54]
Like in title, I can't see how can I get attachments from homework.
That's how it looks on vulcan website:

<img src="https://i.imgur.com/7uWtjo0.png" alt="homework" />

**Comment by Antoni-Czaplicki** [comment]
Yes, but you have to use the new API (hebe).

**Comment by Rei-666** [comment]
Where can I find anything about this API?

**Comment by Antoni-Czaplicki** [comment]
Currently there are problems with online documentation, download the repository and run (on Windows) docs\make html in the downloaded folder. Then you can find docs in docs\build.

**Comment by Antoni-Czaplicki** [comment]
https://vulcan-api.000webhostapp.com/

**Comment by Rei-666** [comment]
Thank you so much! I will try it.
