### ISSUE TITLE
Secondname must be class str, got None that is a class NoneType.

### ISSUE THREAD

**Issue by Rei-666** [kapi2289/vulcan-api#55]
Like in title, I get TypeError when I'm trying to select student using vulcan hebe api.

`TypeError: ("'second_name' must be (<class 'str'>,) (got None that is a <class 'NoneType'>)."`

**Comment by Antoni-Czaplicki** [comment]
Please send me your code

**Comment by Rei-666** [comment]
```
async def main():
    keystore_manager = KeystoreFileManager("keystore.json")
    account_manager = AccountFileManager("account.json")

    if not account_manager.account:
        await account_manager.register_and_save(keystore_manager.key, "myToken", "mySymbol", "myPin")

    client = VulcanHebe(keystore_manager.key, account_manager.account)

    await client.select_student()

    await client.close()


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

KeystoreFileManager and AccountFileManager are simple classes for json file handling. You can see all of the code [here](https://github.com/Rei-666/VulcanApi-with-google-spreadsheets/tree/main/VulcanHebe).

**Comment by Antoni-Czaplicki** [comment]
Try this: https://github.com/kapi2289/vulcan-api/pull/56

**Comment by Rei-666** [comment]
#56 still doesn't fix my problem, there is full console log from this error: [click](https://pastebin.com/AwYAzN31)

**Comment by Antoni-Czaplicki** [comment]
Yes, probably the easiest (but I'm not sure if the best) option is to replace `second_name: str = StringField(key="SecondName", required=False)` by `second_name: str = StringField(key="SecondName", default="")`, please try this and give me a feedback.

**Comment by Rei-666** [comment]
Nevermind, I installed new version of vulcan-api in wrong virtual environment, now everything works perfectly with #56, thank you so much for help, again!
