### ISSUE TITLE
Vulcan.create throwing error

### ISSUE THREAD

**Issue by askrealcookie** [kapi2289/vulcan-api#72]
PyCharm was throwing error at `from vulcan import Vulcan` saying that it can't find Vulcan in vulcan. I am sure I installed proper vulcan. Because of this I just made quick .py file, but I get error that there is no .create in Vulcan.
![Code_fneAIG1T7m](https://user-images.githubusercontent.com/47023698/109150255-e52a7080-7768-11eb-906c-897b5f479092.png)
Any ideas? I have no much experience with pycharm/overall python. thanks in advance!

**Comment by kuba2k2** [comment]
There is no such method as `create`. Please refer to the documentation for details on how to create a keystore and register it to an account.

**Comment by askrealcookie** [comment]
oh, yeah, you're right, this is deprecated method. Thanks.
