### ISSUE TITLE
Reading messages in new api

### ISSUE THREAD

**Issue by jakex7** [kapi2289/vulcan-api#78]
Hi, i wanted to handle reading message like it was in old api but it seems that the new one has missing that feature.
Are there any progress in implementing messages handling at this time? What's the estimated time of releasing?

**Comment by SZKYTU** [comment]
I need that function too.

**Comment by Antoni-Czaplicki** [comment]
Currently nobody is working on it - if you need it, you can: 
a) wait for someone to do it
b) do it yourself

**Comment by Antoni-Czaplicki** [comment]
Please test this PR: #80

**Comment by kuba2k2** [comment]
@jakex7 The feature is now merged and available in v2.0.0. Please, test it out and close this issue if resolved.
