### ISSUE TITLE
RuntimeWarning: coroutine 'Account.register' was never awaited

### ISSUE THREAD

**Issue by edikiuspro** [kapi2289/vulcan-api#81]
f.write(account.as_json)
AttributeError: 'coroutine' object has no attribute 'as_json'
sys:1: RuntimeWarning: coroutine 'Account.register' was never awaited

**Comment by Antoni-Czaplicki** [comment]
Please show full code

**Comment by edikiuspro** [comment]
@Antoni-Czaplicki 
from vulcan import Keystore,Account,Vulcan
import asyncio
import  json
with open("keystore.json") as f:
    keystore = Keystore.load(json.load(f))
account=Account.register(keystore,"token","symbol","pin")
with open("account.json", "w") as f:
    f.write(account.as_json)
    json.dump(account.as_dict, f)

**Comment by edikiuspro** [comment]
Okay i fixed it with
account=asyncio.get_event_loop().run_until_complete(Account.register(keystore,"token","stmbol","pin"))

**Comment by kuba2k2** [comment]
This is not the way you should use coroutines. Please, read the docs (introduction pages) to use the coroutines as appropriate.
